# Generated by Django 5.2.5 on 2025-08-19 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='معرف التصنيف')),
                ('category_name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
            ],
            options={
                'verbose_name': 'التصنيف',
                'verbose_name_plural': 'التصنيفات',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False, verbose_name='معرف المستودع')),
                ('warehouse_name', models.CharField(max_length=100, verbose_name='اسم المستودع')),
            ],
            options={
                'verbose_name': 'المستودع',
                'verbose_name_plural': 'المستودعات',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='معرف المادة')),
                ('item_name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('unit', models.CharField(max_length=50, verbose_name='الوحدة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_system.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'المادة',
                'verbose_name_plural': 'المواد',
            },
        ),
    ]
